return {
    require("shail.plugin_config.color"),
    require("shail.plugin_config.lua-line"),
    require("shail.plugin_config.nvim-tree"),
    require("shail.plugin_config.tree-sitter"),
    require("shail.plugin_config.lsp"),
    require("shail.plugin_config.nvim-surround"),
    require("shail.plugin_config.autopair"),
    -- require("shail.plugin_config.autotag"),
    require("shail.plugin_config.barbar"),
    require("shail.plugin_config.telescope"),
    require("shail.plugin_config.vCooler"),
    require("shail.plugin_config.emmet"),
    require("shail.plugin_config.conform"),
}
